version: '3'
services:

  poly-client:
    build:
      context: .
      dockerfile: cmd/poly-client/Dockerfile
    environment:
      - REDIS_PW=${REDIS_PW}
      - REDIS_ADDR=${REDIS_ADDR}
      - STORK_CREDENTIALS=${STORK_CREDENTIALS}
      - STORK_ENDPOINT=${STORK_ENDPOINT}
    depends_on:
      - redis-timeseries
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  pyth-client:
    build:
      context: .
      dockerfile: cmd/pyth-client/Dockerfile
    environment:
      - REDIS_PW=${REDIS_PW}
      - REDIS_ADDR=${REDIS_ADDR}
      - CONFIG_PATH=/prices_conf
    depends_on:
      - redis-timeseries
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - prices_conf

  v2-client:
    build:
      context: .
      dockerfile: cmd/v2-client/Dockerfile
    environment:
      - REDIS_PW=${REDIS_PW}
      - REDIS_ADDR=${REDIS_ADDR}
      - CONFIG_RPC=/rpc_conf
      - CHAIN_ID=${CHAIN_ID}
    depends_on:
      - redis-timeseries
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - rpc_conf
      
  v3-client:
    build:
      context: .
      dockerfile: cmd/v3-client/Dockerfile
    environment:
      - REDIS_PW=${REDIS_PW}
      - REDIS_ADDR=${REDIS_ADDR}
      - CONFIG_RPC=/rpc_conf
      - CHAIN_ID=${CHAIN_ID}
    depends_on:
      - redis-timeseries
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - rpc_conf

  ws-server:
    build:
      context: .
      dockerfile: cmd/ws-server/Dockerfile
    environment:
      - REDIS_PW=${REDIS_PW}
      - REDIS_ADDR=${REDIS_ADDR}
      - CONFIG_PATH=/prices_conf
    depends_on:
      - redis-timeseries
    ports:
      - 8080:8080
    networks:
     - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - prices_conf

  redis-timeseries:
    image: redis/redis-stack-server:latest
    command: redis-stack-server --requirepass ${REDIS_PW}
    environment:
      - TZ=UTC
    ports:
      - "6379:6379"
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"
configs:
  prices_conf:
    file: ./config/prices.config.json
  rpc_conf:
    file: ./config/rpc_conf.json
networks:
  app-net:
